language: node_js
node_js:
- iojs
- '8'
deploy:
  provider: heroku
  api_key:
    secure: DBJIudoFGcKQkDB1o/1AIX9s9wXK17afnx1AVVfBERHHMb14gGRtG+Z09rhYnviNL2Le25NPexkmnLxYbfDDYgFFNfSBWD/wzG97AmLgQA2lwh2OUGMC097CkfILx27EUoQwjNv8xIAlL63rmfOXvs06T8MumFpmKlSiHeboTj32TNcr8Yxipa+f3Kd6uTydZx5RQTgAJV8EtdT2LGQA6X35yoOq37HmYgMBlH4roxJ1s0RlupYNA3WMEU5FYf+Zv/0waH6vilr6E0J0SmtfdI8NyOXQg3bNBrjNWhUuu0HFLpMLvK0wlI4aEW1F0gWGTye/1NA64ikxlRFYlEzBYqjJ5euO+JbL/JGl7NYL+1N1vwqPtJeHKoHpMOzpTckT1meZdYov0D+/qkWqAT9NTbNjCu+XdCA0LcAP4M8UqAic0bRMeYExtpTajjERGZqXUxi/VgGAwAt2aCR0T/U9FjFk5VWvLG3dNvSBpMX73CkCmm5JQlTsCz2+bpK8jjE5SyQmkkkx6EeE1aFJ1KOwA+ITn2x4GXHHVNKybSBCHlG12qy5ZWSwnbh1w7Z6G1KhXpADQuS8DTFCeeNnYw3oeSnrTWk4nGTgrb5366aT+HvkMkp7DrUzz+paFOuQIhUa7DqMs/zOLFZTAMtayWJbReK/BTc7naAG4EwX37OBrtk=
